### ISSUE TITLE
[EPIC] Invenio accounts CSRF and KVSession 

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-accounts#320]
**Cleanup**
- [ ] SQLAlchemy-Utils dependency is migrated/inherited to `invenio-db` [PR](https://github.com/inveniosoftware/invenio-accounts/pull/319)

**CSRF**
- [ ] Requires [bumping Invenio-REST version](https://github.com/inveniosoftware/invenio-accounts/issues/311)
- [x] [PR](https://github.com/inveniosoftware/invenio-accounts/pull/316) Has been closed in favour of:
    - [ ] [CSRF token reset](https://github.com/inveniosoftware/invenio-accounts/pull/318/files)
    - [ ] [KVSession storage only for authenticated users](https://github.com/inveniosoftware/invenio-accounts/pull/316/files)

**Test in Cookiecutter**
- [ ] According to [this issue](https://github.com/inveniosoftware/invenio-accounts/issues/289)

**Release**
- [ ] Male [Invenio-Accounts v1.2.2](https://github.com/inveniosoftware/invenio-accounts/issues/310) release.

----

Current status: https://github.com/inveniosoftware/flask-kvsession/issues/7

Potential cause of the issue:

- The configuration should not be set in cookiecutter: 
    - [ ] [Cookiecutter PR should be closed](https://github.com/inveniosoftware/cookiecutter-invenio-instance/pull/222/files/)
    - [ ] Invenio-Accounts should be fixed to load configuration properly. Add `SESSIONS_` and other potential prefixes (`RECAPTCHA`, check config.py) to [`config_apps`](https://github.com/inveniosoftware/invenio-accounts/blob/master/invenio_accounts/ext.py#L239) list.
